#!/usr/bin/env bash

HOST_VLAN_CONTROLLER=192.168.42.1
OPENSTACK_ADMIN_PROJECT=admin
KEYSTONE_ADMIN_USER=admin
KEYSTONE_ADMIN_PASS=admin_password
KEYSTONE_INTERNAL_ENDPOINT=http://$HOST_VLAN_CONTROLLER:5000

  export OS_IDENTITY_API_VERSION=3
  export OS_PROJECT_DOMAIN_ID=default
  export OS_PROJECT_DOMAIN_NAME=Default
  export OS_USER_DOMAIN_ID=default
  export OS_USER_DOMAIN_NAME=Default
  export OS_PROJECT_NAME=${OPENSTACK_ADMIN_PROJECT}
  export OS_USERNAME=${KEYSTONE_ADMIN_USER}
  export OS_PASSWORD=${KEYSTONE_ADMIN_PASS}
  export OS_AUTH_URL=${KEYSTONE_INTERNAL_ENDPOINT}/v3
  export OS_INTERFACE=internal

openstack
