version: "3.9"
services:
  mariadb:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    command: --log-warning=1 --max-connections=20000
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8000:80"
    env_file:
      - .env
    links:
      - mariadb
    depends_on:
      - mariadb
  keystone:
    build:
      context: ./keystone
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${KEYSTONE_PORT}:${KEYSTONE_PORT}"
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
