version: "3.9"

services:
    mariadb:
        build:
            context: ./database
            dockerfile: Dockerfile
        volumes:
            - ./data/mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            os-internal:
                aliases:
                    - mariadb
        restart: unless-stopped
        # About max-connection:
        #   By default, all OpenStack components start a set number of workers based on the number of CPUs that a system has. The system calculates the number of workers to start by using the following formula: NUM_CPUs / 2. The system calculates a minimum of 2 workers, and a maximum of 4 workers for each function.
        command: --log-warning=1 --max-connections=512

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8000:80"
        env_file:
            - .env
        networks:
            os-internal: {}
        depends_on:
            - mariadb

    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"
        env_file:
            - .env
        networks:
            os-internal: {}

    rabbitmq:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
            args:
                - RABBIT_PASS
        env_file:
            - .env
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15691:15691"
            - "15692:15692"
            - "25672:25672"
        networks:
            os-internal: {}

    keystone:
        build:
            context: ./keystone
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "5000:5000"
        networks:
            os-internal:
                aliases:
                    - $HOST_INTERNAL_KEYSTONE
        # volumes:
        #   - ./log/keystone:/var/log/keystone
        depends_on:
            mariadb:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        stop_signal: SIGKILL

    glance:
        build:
            context: ./glance
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "9292:9292"
        networks:
            os-internal:
                aliases:
                    - $HOST_INTERNAL_GLANCE
        volumes:
            - ./data/glance/images:/var/lib/glance/images
            # - ./log/glance:/var/log/glance
        depends_on:
            mariadb:
                condition: service_healthy
            keystone:
                condition: service_healthy
        stop_signal: SIGKILL

    placement-api:
        build:
            context: ./placement-api
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8778:8778"
        networks:
            os-internal:
                aliases:
                    - $HOST_INTERNAL_PLACEMENT_API
        depends_on:
            keystone:
                condition: service_healthy
        stop_signal: SIGKILL

    nova:
        build:
            context: ./nova
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8774:8774"
        networks:
            os-internal:
                aliases:
                    - $HOST_INTERNAL_NOVA
        depends_on:
            keystone:
                condition: service_healthy
        stop_signal: SIGKILL

    neutron:
        build:
            context: ./neutron
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "9696:9696"
        networks:
            os-internal:
                aliases:
                    - $HOST_INTERNAL_NEUTRON
        depends_on:
            mariadb:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            keystone:
                condition: service_healthy
            nova:
                condition: service_healthy
        stop_signal: SIGKILL

    horizon:
        build:
            context: ./horizon
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "80:80"
        networks:
            os-internal:
                aliases:
                    - $HOST_INTERNAL_HORIZON
        depends_on:
            keystone:
                condition: service_healthy
            glance:
                condition: service_healthy
            placement-api:
                condition: service_healthy
            nova:
                condition: service_healthy
            neutron:
                condition: service_healthy
        stop_signal: SIGKILL

    cinder:
        build:
            context: ./cinder
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8776:8776"
        networks:
            os-internal:
                aliases:
                  - $HOST_INTERNAL_CINDER
        depends_on:
            keystone:
                condition: service_healthy
            mariadb:
                condition: service_healthy
        stop_signal: SIGKILL

networks:
    os-internal:
        ipam:
            driver: default
            config:
                - subnet: 10.0.2.0/24
