version: "3.9"
services:
  mariadb:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    command: --log-warning=1 --max-connections=20000
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8000:80"
    env_file:
      - .env
    links:
      - mariadb
    depends_on:
      - mariadb
  keystone:
    build:
      context: ./keystone
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - mariadb
    volumes:
      - ./log/keystone:/var/log/keystone
    depends_on:
      mariadb:
        condition: service_healthy
  glance:
    build:
      context: ./glance
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9292:9292"
    links:
      - mariadb
      - "keystone:keystone-server"
    volumes:
      - ./log/glance:/var/log/glance
    depends_on:
      mariadb:
        condition: service_healthy
      keystone:
        condition: service_healthy
