#!/bin/bash

cat > /docker-entrypoint-initdb.d/000-create-users.sql << EOF
CREATE DATABASE \`$KEYSTONE_DATABASE_SCHEME\`;
CREATE USER '$KEYSTONE_DATABASE_USER'@'%' IDENTIFIED BY '$KEYSTONE_DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON \`$KEYSTONE_DATABASE_SCHEME\`.* TO '$KEYSTONE_DATABASE_USER'@'%';
FLUSH PRIVILEGES;
CREATE DATABASE \`$PLACEMENT_DATABASE_SCHEME\`;
CREATE USER '$PLACEMENT_DATABASE_USER'@'%' IDENTIFIED BY '$PLACEMENT_DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON \`$PLACEMENT_DATABASE_SCHEME\`.* TO '$PLACEMENT_DATABASE_USER'@'%';
FLUSH PRIVILEGES;
EOF

exec "docker-entrypoint.sh" $@
