#!/bin/bash

cat > /docker-entrypoint-initdb.d/000-create-users.sql << EOF
CREATE DATABASE \`$KEYSTONE_DATABASE_SCHEME\`;
CREATE DATABASE \`$GLANCE_DATABASE_SCHEME\`;

CREATE USER '$KEYSTONE_DATABASE_USER'@'%' IDENTIFIED BY '$KEYSTONE_DATABASE_PASSWORD';
CREATE USER '$GLANCE_DATABASE_USER'@'%' IDENTIFIED BY '$GLANCE_DATABASE_PASSWORD';

GRANT ALL PRIVILEGES ON \`$KEYSTONE_DATABASE_SCHEME\`.* TO '$KEYSTONE_DATABASE_USER'@'%';
GRANT ALL PRIVILEGES ON \`$GLANCE_DATABASE_SCHEME\`.* TO '$GLANCE_DATABASE_USER'@'%';

FLUSH PRIVILEGES;
EOF

exec "docker-entrypoint.sh" $@
